services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zikula\Bundle\DynamicFormPropertyBundle\:
        resource: '../../*'
        exclude:
            - '../../{bootstrap.php,Tests,vendor}'
            - '../../Form/EventListener/*'
